In [4]:
import numpy as np
#1d array
a=np.array([1,2,3])
#2d array
b= np.array([[[3,4,5],[4,6,7]],[[5,6,7],[6,7,8]]])
#3d array
c = np.array([[[3,7,8], [5,8,9]],[[3,6,8],[6,8,9]],[[8,9,7],[6,8,9]]])
print(a)
print(b)
print(c)

[1 2 3]
[[[3 4 5]
  [4 6 7]]

 [[5 6 7]
  [6 7 8]]]
[[[3 7 8]
  [5 8 9]]

 [[3 6 8]
  [6 8 9]]

 [[8 9 7]
  [6 8 9]]]


In [5]:
#slicing operation

print (a[:2])

[1 2]


In [7]:
print(b[1:3])


[[[5 6 7]
  [6 7 8]]]


In [8]:
print(c[3:])

[]


In [12]:
a2= np.array([4,5,6])
y=a+a2
print(y)

[5 7 9]


In [13]:
y=a-a2
y

array([-3, -3, -3])

In [14]:
a*a2

array([ 4, 10, 18])

In [15]:
a/a2

array([0.25, 0.4 , 0.5 ])

In [17]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [20]:
#create array using different functions 
arr1 = np.array([1, 2, 3, 4, 5])
np.arange(1,5,1)








array([1, 2, 3, 4])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.random.randn(2,3)

array([[-1.23729191,  0.57289467,  0.73085832],
       [ 0.08135904, -0.11117215,  0.44883392]])

In [45]:
y=a.reshape(3)
y

array([1, 2, 3])

In [46]:
split = np.array_split(arr1,3)
print(split)

[array([1, 2]), array([3, 4]), array([5])]


In [49]:
concatenat = np.concatenate((a,a2))
print(concatenat)

[1 2 3 4 5 6]


In [50]:
np.mean(a)

2.0

In [52]:
np.median(a)

2.0

In [53]:
np.var(a)

0.6666666666666666

In [54]:
np.std(a)

0.816496580927726

In [55]:
np.min(a)

1

In [56]:
np.max(a)

3

In [57]:

#finding indices

np.argmin(a)

0

In [58]:
np.argmax(a)

2

In [59]:
#compute sum and product of an array

np.sum(a)

6

In [61]:
np.prod(a)

6

In [64]:
#
matrix = np.array([[1, 2],[3,4]])

np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
np.linalg.det(matrix)

-2.0000000000000004