## Create a 1D array, a 2D array, and a 3D array.

In [71]:
import numpy as np
import pandas as pd

In [4]:
array1d = np.array([1,2,3,4,5])
print(array1d)

[1 2 3 4 5]


In [8]:
# 2D array
array2d = np.array([[1,2],[3,4]])
print(array2d)

[[1 2]
 [3 4]]


In [102]:
# 3D array
array3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Create arrays using different functions: arange, linspace, zeros, ones, eye, random.

In [14]:
array_using_arange = np.arange(1,11)
print(array_using_arange)
print(len(array_using_arange))

[ 1  2  3  4  5  6  7  8  9 10]
10


In [16]:
# array_using_linespace = np.linespace(11,21)
# print(array_using_linespace)
# print(len(array_using_linespace))

In [23]:
array_of_zeros_1d = np.zeros(4)
print(array_of_zeros)
array_of_zeros_2d = np.zeros((5,4))
print(array_of_zeros_2d)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
array_of_ones_1d = np.ones(4)
print(array_of_ones_1d)
array_of_ones_2d = np.ones((5,4))
print(array_of_ones_2d)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
array_of_random = np.random.rand(5)
print(array_of_random)
# if we write a number in rand function it will generate values of that number 
# and if we write (2,3) then it means that it will generate 2 array of 3 elements as a whole
three_array_of_random = np.random.rand(3,4)
print(f'array brfore reshape\n{three_array_of_random}')
three_array_of_random = three_array_of_random.reshape(2,6)
print(f"array after reshape in 2 array with 6 elements \n{three_array_of_random}")

[0.35185738 0.50006647 0.59399534 0.9885128  0.4686805 ]
array brfore reshape
[[0.36569729 0.92465468 0.97250799 0.87492217]
 [0.26481017 0.20172303 0.58387723 0.8625639 ]
 [0.64009895 0.7275495  0.66233848 0.25005749]]
array after reshape in 2 array with 6 elements 
[[0.36569729 0.92465468 0.97250799 0.87492217 0.26481017 0.20172303]
 [0.58387723 0.8625639  0.64009895 0.7275495  0.66233848 0.25005749]]


## Concatenate and split arrays.

In [56]:
array1 = np.random.rand()
print(array1)
array2 = np.random.rand(6)
print(array2)
print('if we want to concatenate two array\nwe have to keep in mind that all arrays should be in same size')
sum_of_arrays = array1+array2
print(f'sum of\n{array1} \nand\n{array2} \nis\n{sum_of_arrays}')


0.3162265988109504
[0.94728015 0.02676774 0.65305161 0.97653336 0.6833862  0.23427374]
if we want to concatenate two array
we have to keep in mind that all arrays should be in same size
sum of
0.3162265988109504 
and
[0.94728015 0.02676774 0.65305161 0.97653336 0.6833862  0.23427374] 
is
[1.26350675 0.34299434 0.96927821 1.29275996 0.9996128  0.55050034]


In [62]:
split_array = np.split(array_using_arange, 2)
print(split_array)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


# Statistical Operations

In [64]:
# mean of array
print(f'the mean of the array is {np.mean(array1d)}')
# median of array
print(f'the mean of the array is {np.median(array1d)}')
# mean of array
print(f'the std of the array is {np.std(array1d)}')
# variance of array
print(f'the variance of the array is {np.var(array1d)}')

the mean of the array is 3.0
the mean of the array is 3.0
the std of the array is 1.4142135623730951
the variance of the array is 2.0


In [75]:
# the minimum and maximum values in an array along with their indices.
print(array_using_arange)
print(f'the minimum value in the array is\n{np.min(array_using_arange)}')
print(f'the maximum value in the array is\n{np.max(array_using_arange)}')

[ 1  2  3  4  5  6  7  8  9 10]
the minimum value in the array is
1
the maximum value in the array is
10


In [78]:
sum_of_array = np.sum(array_using_arange)
print(array_using_arange)
print(f'the sum of the array is {sum_of_array}')

[ 1  2  3  4  5  6  7  8  9 10]
the sum of the array is 55


## Broadcasting

In [80]:
broadcast_mul2 = 2*(array_using_arange)
print(broadcast_mul2)

[ 2  4  6  8 10 12 14 16 18 20]


In [83]:
broadcastdiv2 = 2/array_using_arange
print(broadcastdiv2)

[2.         1.         0.66666667 0.5        0.4        0.33333333
 0.28571429 0.25       0.22222222 0.2       ]


## Linear Algebra

### Perform matrix multiplication.

In [88]:
print(array3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [90]:
mul_3d_array = 3*array3d
print(mul_3d_array)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [97]:
determinant_3d_array = np.linalg.det(array3d)
print(f"the determinant of the\n{array3d}\nis {determinant_3d_array}")

the determinant of the
[[1 2 3]
 [4 5 6]
 [7 8 9]]
is -9.51619735392994e-16


In [100]:
inverse_3d_array = np.linalg.inv(array3d)
print(inverse_3d_array)
# print(f"the determinant of the\n{array3d}\nis {determinant_3d_array}")

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [105]:
eigen_3d_array = np.linalg.eig(array3d)
print(eigen_3d_array)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
