In [2]:
### Numpy Assignment No.1

#### Q1: Basic Array Operations


In [3]:
import pandas as pd
import numpy as np

In [4]:
#Create a 1D array, a 2D array, and a 3D array.
# One Demensional Array
oneD = np.array([1, 2, 3, 4]) # 1D array 
print(oneD) 

[1 2 3 4]


In [5]:
# Two Demensional Array
twoD = np.array([[1, 2], [3, 4]]) # 2D Array
#twoD
print(twoD)

[[1 2]
 [3 4]]


In [6]:
# Three Demensional Array
threeD = np.array([[2, 4], [6, 8], [10, 12]]) # 3D Array
print(threeD)
threeD

[[ 2  4]
 [ 6  8]
 [10 12]]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [7]:
#Perform slicing operations on arrays.
slicing = np.arange(10)**3 # create array cube by arange function 
#print(slicing)
#print(slicing[4:8]) #array slincing 
sli = np.arange(10)**3
sli[2:6:2]
sli
slicing[:8:2] = -1000 
#slicing

In [8]:
#Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division)
art1 = np.array([[2, 4, 6],[1, 2, 3]])
art2 = np.array([[1, 3, 5],[4, 5, 6]])
art3 = np.array([[6, 7, 8],[2, 6, 10]])
art1 + art2 + art3 # Addition of array

array([[ 9, 14, 19],
       [ 7, 13, 19]])

In [9]:
art1 - art2 - art3 # Subtraction of array


array([[ -5,  -6,  -7],
       [ -5,  -9, -13]])

In [10]:
art1 * art2 * art3 # Multiplication of array


array([[ 12,  84, 240],
       [  8,  60, 180]])

In [11]:
art1 / art2 / art3 # division of array


array([[0.33333333, 0.19047619, 0.15      ],
       [0.125     , 0.06666667, 0.05      ]])

#### Q2: Array Creation and Manipulation


In [12]:
#Create arrays using different functions: arange, linspace, zeros, ones, eye, random.
zero = np.zeros(5) # using simple zero function
print(zero)
zero = np.zeros((10,), dtype=int)
#zero = np.zeros((2,2), dtype=[('x', 'i4'), ('y', 'i4')]) # using zero function 
zero

[0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#Reshape an array.
arange_arr = np.arange(10,30,2) # create array between 10 to 30 
reshape_arr = arange_arr.reshape(2,5)
print("Arry is:", arange_arr)
print("Reshaped array is:", reshape_arr)

Arry is: [10 12 14 16 18 20 22 24 26 28]
Reshaped array is: [[10 12 14 16 18]
 [20 22 24 26 28]]


In [14]:
#Concatenate and split arrays.
arr1 = np.array([4, 6, 8, 10]) # create Array one
arr2 = np.array([1, 2, 3, 4]) # create array two
concatenate_arr = np.concatenate((arr1,arr2), axis= 0) # concatenate both array with concatenate function
print("concatenate array:", concatenate_arr)

concatenate array: [ 4  6  8 10  1  2  3  4]


#### Q3: Statistical Operations

In [15]:
#Compute mean, median, variance, and standard deviation of an array.
# Mean standard deviation of an array
state_arr = np.arange(50,100,5)  # create array value 10 between 50 to 160 
mean_arr = np.mean(state_arr) # make mean of array with mean function
print("Original array: ", state_arr)
print("Mean: ", mean_arr)

Original array:  [50 55 60 65 70 75 80 85 90 95]
Mean:  72.5


In [16]:
# Median standard deviation of an array
state_arr1 = np.arange(1,36,2) # create arry of 18 value from 1 to 36
reshape_arr1 = state_arr1.reshape(3,6) # reshape the arry
median_arr = np.median(reshape_arr1, axis=0) # median of arry
print("original of the array is: ", state_arr)
print("reshaped array is: ", reshape_arr1)
print("Median of the array is: ", median_arr)


original of the array is:  [50 55 60 65 70 75 80 85 90 95]
reshaped array is:  [[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]
 [25 27 29 31 33 35]]
Median of the array is:  [13. 15. 17. 19. 21. 23.]


In [17]:
#variance standard deviation of an array
state_arr2 = np.arange(4,16,2)# create arry of 7 value from 4 to 16
variance = state_arr2.var() # apply vraience function
print("original array is: ", state_arr2)
print("Variance of the array is: ", variance)
print("direct variance", np.var([2, 4, 6])) # we can find direct varienace

original array is:  [ 4  6  8 10 12 14]
Variance of the array is:  11.666666666666666
direct variance 2.6666666666666665


In [18]:
#standard deviation of an array
state_arr3 = np.arange(20,80,4) # create random arry of 10 value from 20 to 80
#std = sqrt(mean(abs(x - x.mean())**2)) # std formula
sd = state_arr3.std() # standard deviation function
print("original array:",state_arr3)
print("standard deviation of array:",sd)

original array: [20 24 28 32 36 40 44 48 52 56 60 64 68 72 76]
standard deviation of array: 17.281975195754296


In [19]:
#Find the minimum and maximum values in an array along with their indices.
# minimum values in an array
arr3 = np.random.randint(20, 100, 10, dtype=int) 
mini = arr3.min()
print("Array: ", arr3)
print("Minimum value: ", mini)

Array:  [47 89 70 33 79 35 32 59 59 71]
Minimum value:  32


In [20]:
#maximum values in an array
arr3 = np.random.randint(20, 100, 10, dtype=int) 
maxi = arr3.max()
print("Array: ", arr3)
print("Max value: ", maxi)

Array:  [66 95 28 73 26 85 54 70 98 76]
Max value:  98


In [44]:
#Compute the sum and product of array elements.
arr_element = np.random.randint(50,452,12) # create random array 
np.random.seed(arr_element) # random array cannot change element value
reshape_arry = arr_element.reshape(3,4) #reshape the array
sum_arr = np.sum(arr_element) # sum of all elements of array
product_arr = np.prod(arr_element) # product of all elements of array
print("orignal array is:",arr_element)
print("reshaped array is:",reshape_arry)
print("sum of array elements is:",sum_arr)
print("product of array elements is:",product_arr)

orignal array is: [411 111 228 171 319 424 212 297 171 311 188 211]
reshaped array is: [[411 111 228 171]
 [319 424 212 297]
 [171 311 188 211]]
sum of array elements is: 3054
product of array elements is: -1416924672


#### Q4: Broadcasting


In [54]:
#Demonstrate broadcasting with examples of different shapes of arrays.
dif_arr1 = np.random.randint(10,90,12)
np.random.seed(dif_arr1)
reshape_arr3 = dif_arr1.reshape(4,3)
dif_arr2 = np.arange(10,19,3)
arr_sum = sum(reshape_arr3+dif_arr2)
print(" array one is:",reshape_arr3)
print("array two is",dif_arr2)
print("broadcasting of array is:",arr_sum)


 array one is: [[59 80 61]
 [54 67 18]
 [51 85 82]
 [30 21 23]]
array two is [10 13 16]
broadcasting of array is: [234 305 248]


In [23]:
    #Explain the concept of broadcasting and how it works in NumPy.

#### Q5: Linear Algebra

In [55]:
#Perform matrix multiplication.
mat1 = np.array([[2,4,6],[3,6,9]])
mat2 = np.array([[1,2],[3,4],[5,6]])
print(np.dot(mat1,mat2))

[[44 56]
 [66 84]]


In [58]:
#Compute the determinant of a matrix.#Compute the eigenvalues of a matrix.
mat_arr = np.array([[5,6,4],[3,7,6],[7,9,4]])
deter = np.linalg.det(mat_arr)
print("Determinant of the matrix is: ", deter)

Determinant of the matrix is:  -37.99999999999999


In [59]:
#Compute the inverse of a matrix.
inr = np.linalg.inv(mat_arr)
print("Inverse of the matrix:", inr)

Inverse of the matrix: [[ 0.68421053 -0.31578947 -0.21052632]
 [-0.78947368  0.21052632  0.47368421]
 [ 0.57894737  0.07894737 -0.44736842]]


In [70]:
#Solve a system of linear equations.
mat1 =np.array([[1,1,1],[0,2,5],[2,5,-1]])
mat2 = np.array([[6],[-4],[27]])
solve = np.linalg.solve(mat1,mat2)
print("solve linear equation is:",solve)

solve linear equation is: [[ 5.]
 [ 3.]
 [-2.]]


#### Q6: Advanced Indexing and Slicing


In [75]:
#Use Boolean indexing to filter an array.
ind_arr  = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
#bool_arr = np.array([[True, False, True],[False, True, False],[True,True,True,],[False,False,False]])
bool_arr1 = ind_arr[ind_arr>5]
print("boolanj array:", bool_arr1)


boolanj array: [ 6  7  8  9 10 11]


In [91]:
#Use fancy indexing to select specific elements from an array.
#r = np.random.RandomState(42)

x = np.random.randint(100, size=10)
print(x)
#Suppose we want to access three different elements. We could do it like this:
[x[3], x[7], x[2]]
#But this is not very efficient. We can do it more efficiently using fancy indexing.
#Alternatively, we can pass a single list or array of indices to obtain the same result:
deff = x[[3, 7, 2]]
print("same result",deff)
#when using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the arraybeing indexed:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

[72 95 96 57 32 99 68 47 90 11]
same result [57 47 96]


array([[57, 47],
       [32, 99]])

In [95]:
#Perform advanced slicing operations.
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print ('Our array is:')
print (a)
print ('\n')
# this returns array of items in the second column
print ('The items in the second column are:')
print (a[...,1])
print ('\n')
# Now we will slice all items from the second row
print ('The items in the second row are:')
print (a[1,...])
print ('\n')
# Now we will slice all items from column 1 onwards
print ('The items column 1 onwards are:')
print (a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


#### Q7: Random Sampling

In [103]:
#Generate random numbers from different distributions.
rand_num = np.random.normal(0, 1, 15)

# Printing a message indicating 15 random numbers from a standard normal distribution
print("15 random numbers from a standard normal distribution:")

# Printing the array of 15 random numbers
print(rand_num) 

15 random numbers from a standard normal distribution:
[-0.64112518 -0.38471116 -1.18926089  2.39534306 -1.97095032  0.63827922
  0.44728479  0.77226038  0.32488065 -1.4270401   2.84400004  1.05102965
  0.74377258  0.62882613  0.93567672]


In [102]:
#Create random samples from a dataset.
out_arr = np.random.sample(size=(3, 3))
print("Output 2D Array filled with random floats : ", out_arr)

Output 2D Array filled with random floats :  [[0.14259395 0.51103762 0.71635846]
 [0.32405706 0.71003999 0.24854971]
 [0.90943579 0.09761429 0.64698723]]


In [101]:
#Perform random shuffling of an array.
g1 = np.arange(10) 
print("g1",g1)
# Using shuffle() method 
g2 = np.random.shuffle(g1) 
  
print("g2",g2)



g1 [0 1 2 3 4 5 6 7 8 9]
g2 None


## Assignment as done