# Assignment Numpy

## Basic Array Operations

In [3]:
import numpy as np
# Create a 1D array, a 2D array, and a 3D array.
arr1D = np.array([2, 3, 4, 5, 6])
arr2D = np.array([[4, 3, 5, 9, 7], [3, 6, 7, 2, 5]])
arr3D = np.array([[2, 3, 4, 4, 5], [3, 4, 5, 6,2], [3,6, 7, 5, 3]])

print(arr1D, arr2D, arr3D)


[2 3 4 5 6] [[4 3 5 9 7]
 [3 6 7 2 5]] [[2 3 4 4 5]
 [3 4 5 6 2]
 [3 6 7 5 3]]


In [12]:
# Perform slicing operations on arrays.
arr1D[1:4:2]

array([3, 5])

In [17]:
# Perform basic arithmetic operations on arrays (addition, subtraction, multiplication, division).
add_arrays = np.array([3, 5, 7, -5, 3]) + arr1D
sub_arrays = add_arrays - np.array([4, 2, 4, 0, -3])
mul_arrays = arr2D * 3
div_arrays = arr3D / 4

print(div_arrays)


[[0.5  0.75 1.   1.   1.25]
 [0.75 1.   1.25 1.5  0.5 ]
 [0.75 1.5  1.75 1.25 0.75]]


## Array Creation and Manipulation

In [47]:
# Create arrays using different functions: arange, linspace, zeros, ones, eye, random.
arr_arange = np.arange(3, 40, 3)
arr_linspc = np.linspace(1.2, 40.8, 6)
arr_zeros = np.zeros((3, 4))
arr_eye = np.eye(4, dtype=int)
arr_rand = np.random.rand(3, 4)

print(arr_rand)

[[0.1617206  0.02018064 0.36544525 0.00857545]
 [0.72020228 0.51193693 0.31307546 0.69294939]
 [0.75346226 0.18762375 0.58034296 0.09839628]]


In [49]:
# Reshape an array.
arr = np.array([2, 34, 5, 5, 23, 53, 56, -34, 54])
arr.reshape(3, 3)

array([[  2,  34,   5],
       [  5,  23,  53],
       [ 56, -34,  54]])

In [61]:
# Concatenate and split arrays.
arr_full = np.array([4, 3, 54, 6, 86, 34, 242, 34])
np.concatenate((arr_full, arr))
np.array_split(arr_full, 5)

[array([4, 3]), array([54,  6]), array([86, 34]), array([242]), array([34])]

## Statistical Operations

In [72]:
# Compute mean, median, variance, and standard deviation of an array.
mean = arr_full.mean()
median = np.median(arr_full)
var = np.var(arr_full)
sd = np.std(arr_full)

5556.609375


In [78]:
# Find the minimum and maximum values in an array along with their indices.
min_val = np.min(arr_full)
min_val_index = np.argmin(arr_full)
max_val = np.max(arr_full)
max_val_index = np.argmax(arr_full)

3 1
242 6


In [ ]:
Compute mean, median, variance, and standard deviation of an array.
Find the minimum and maximum values in an array along with their indices.
Compute the sum and product of array elements.
Broadcasting

Demonstrate broadcasting with examples of different shapes of arrays.
Explain the concept of broadcasting and how it works in NumPy.
Linear Algebra

Perform matrix multiplication.
Compute the determinant, inverse, and eigenvalues of a matrix.
Solve a system of linear equations.
Advanced Indexing and Slicing

Use Boolean indexing to filter an array.
Use fancy indexing to select specific elements from an array.
Perform advanced slicing operations.
Random Sampling

Generate random numbers from different distributions.
Create random samples from a dataset.
Perform random shuffling of an array.