Name: Jahangeer Ali

In [2]:
import pandas as pd
import numpy as np

### Sales Data Analysis

In [60]:
Daily_sales =np.array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140, 180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130, 50, 200, 110, 160, 230])
Daily_sales

array([105, 150, 200, 125, 200, 250, 180, 110, 160, 230, 210, 190, 140,
       180, 200, 120, 170, 334, 190, 100, 150, 210, 180, 130,  50, 200,
       110, 160, 230])

In [61]:
Total_sales=Daily_sales.sum()
Total_sales

4964

In [62]:
Average_sales=Daily_sales.mean()
Average_sales

171.17241379310346

In [63]:
Highest_Day_sales=Daily_sales.argmax()+1
Highest_Day_sales

18

In [64]:
HeighestSale_Amount= Daily_sales.max()
HeighestSale_Amount

334

### Weather Data Processing

In [65]:
Weekly_Temperatures = np.array([[31,43,33,37,32,36,30],
                                [39,42,34,31,36,32,38],
                                [33,41,30,32,35,38,36],
                               ])
Weekly_Temperatures 

array([[31, 43, 33, 37, 32, 36, 30],
       [39, 42, 34, 31, 36, 32, 38],
       [33, 41, 30, 32, 35, 38, 36]])

In [66]:
Veg_temp_Day=Weekly_Temperatures.mean(axis=0)
Veg_temp_Day

array([34.33333333, 42.        , 32.33333333, 33.33333333, 34.33333333,
       35.33333333, 34.66666667])

In [67]:
for day in range(7):
    print(f"Day {day+1}: {Veg_temp_Day[day]:.2f} degrees Celsius")

Day 1: 34.33 degrees Celsius
Day 2: 42.00 degrees Celsius
Day 3: 32.33 degrees Celsius
Day 4: 33.33 degrees Celsius
Day 5: 34.33 degrees Celsius
Day 6: 35.33 degrees Celsius
Day 7: 34.67 degrees Celsius


### Financial Analysis

In [68]:
Prices = np.array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,149, 150, 151])
Prices

array([109, 115, 104, 135, 136, 137, 138, 140, 142, 144, 145, 147, 148,
       149, 150, 151])

In [69]:
Monthly_return = (Prices[-1]-Prices[0])/prices[0]*100
Monthly_return 

38.53211009174312

### Student Grades Analysis

In [70]:
Grades_std = np.array([[70, 95, 88],[75, 60, 80],[80, 89, 92],[81, 77, 65]])
Grades_std

array([[70, 95, 88],
       [75, 60, 80],
       [80, 89, 92],
       [81, 77, 65]])

In [71]:
Avg_grade_pr_std = np.mean(Grades_std, axis=1)
Avg_grade_pr_std

array([84.33333333, 71.66666667, 87.        , 74.33333333])

In [72]:
Class_avg_per_subj = np.mean(Grades_std, axis=0)
Class_avg_per_subj

array([76.5 , 80.25, 81.25])

### Image Processing

In [73]:
img = np.array([[0, 130, 255],[50, 167, 138],[255, 190, 0]])
img

array([[  0, 130, 255],
       [ 50, 167, 138],
       [255, 190,   0]])

In [74]:
#Img range 0 to 1
normalized_img = img / 255.0
normalized_img

array([[0.        , 0.50980392, 1.        ],
       [0.19607843, 0.65490196, 0.54117647],
       [1.        , 0.74509804, 0.        ]])

### Population Growth Analysis

In [75]:
Population_Data = np.array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

Population_Data

array([1700, 1650, 1800, 2300, 1200, 1050, 1300, 1100, 1600, 1500])

In [76]:
annual_growth_rate = np.diff(Population_Data) / Population_Data[:-1] * 100
highest_growth_year = np.argmax(annual_growth_rate) + 1  

In [77]:
annual_growth_rate


array([ -2.94117647,   9.09090909,  27.77777778, -47.82608696,
       -12.5       ,  23.80952381, -15.38461538,  45.45454545,
        -6.25      ])

In [78]:
highest_growth_year

8

Traffic Data Analysis

In [79]:
#Data: 7 days, 24 hrs
Trafic = np.random.randint(20, 170, size=(7, 24))
Trafic 

array([[ 63,  32,  97,  84,  77, 137,  36, 158,  24,  39, 123,  36, 137,
         64, 140, 115, 128, 139, 108,  99,  63, 163, 153,  78],
       [164,  83,  31,  37, 137, 116, 169,  45,  85, 137, 151, 140,  64,
         42,  26, 156,  48, 112, 140,  35,  78,  89,  46,  94],
       [110,  26,  22, 118,  75,  92,  93, 143, 107,  35, 162,  95, 101,
        162, 159, 103,  70,  91, 120,  93, 100,  85,  42, 128],
       [ 74,  76,  63, 121,  35, 107,  54, 117, 116,  30,  80,  27, 168,
         95, 127,  35,  75,  23,  28, 151, 111, 104,  65, 159],
       [ 62, 139,  81, 137,  97, 133, 118,  24,  60, 101, 143,  33,  85,
         75,  70, 151, 155, 114,  77,  82,  34,  47, 118, 156],
       [ 74,  47, 156, 132, 130,  25,  47,  47,  21, 135,  96, 111, 162,
         46, 109,  85, 137,  44,  33, 112, 167, 161,  35,  94],
       [130,  61, 145, 108, 123,  53,  89, 125, 167, 118,  65, 105,  55,
        142,  79,  27,  67,  91, 128, 165, 115,  30,  61, 125]])

In [80]:
total_trafic_per_day = np.sum(Trafic, axis=1)
Busy_hour_in_wk = np.argmax(np.sum(Trafic, axis=0))

In [81]:
total_trafic_per_day 

array([2293, 2225, 2332, 2041, 2292, 2206, 2374])

In [82]:
Busy_hour_in_wk

23

Product Inventory Management:

In [83]:
Stock_levels = np.array([55, 65, 75, 35, 50, 25])


In [84]:
#threshold 50 units
reorder_list = np.where(Stock_levels < 50)[0]

reorder_list

array([3, 5], dtype=int64)


Game Score Analysis

In [85]:
#Data of 5 players and 10 rounds
Score = np.random.randint(80, 320, size=(5, 20))

In [86]:
# Player with highest ave score
highest_avg_scoreplayer = np.argmax(np.mean(Score, axis=1))

# Round with highest T score
highest_total_scorer_ound = np.argmax(np.sum(Score, axis=0))

In [87]:
highest_avg_scoreplayer

2

In [88]:
highest_total_scorer_ound

16

Financial Portfolio Analysis

In [89]:
# 4 assets, 30 days)
Return = np.random.randn(6, 40)

Overall_daily_return = np.mean(Return, axis=0)

# Asset with highest volatility
Highest_volatility_asset = np.argmax(np.std(Return, axis=1))

Overall_daily_return

array([-0.15710292,  0.14693031, -0.11058017,  0.65908172,  0.97625376,
        0.94147998, -0.02241212,  1.06959665, -0.67390103,  0.26145434,
        0.41724281,  0.20696546, -0.24069148,  0.0548523 , -0.43383101,
       -0.15862752, -0.15235866, -0.12334247,  0.72438951,  0.4418869 ,
       -0.19881193, -0.22925297, -0.10824404,  0.31176844, -0.11887717,
        0.26997491, -0.17377332, -0.09354587,  0.16286278, -0.14541745,
        0.08683374,  0.02350369, -0.12078016, -0.46191594,  0.0680416 ,
        0.1783508 , -0.4333544 , -0.34125423, -0.41393265,  0.0436247 ])

In [90]:
Highest_volatility_asset

4