In [1]:
import pandas as pd
import numpy as np


In [4]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
c=np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
d=np.eye((3))
d


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
e=np.arange(0,10,2)
e

array([0, 2, 4, 6, 8])

In [13]:
f=np.linspace(0,1,5)
f

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
a=np.array([1,4,6,8,11])
b=np.array([5,3,7,0,0])
c=np.array([2])
z=a+b
z

array([ 6,  7, 13,  8, 11])

In [15]:
g=np.arange(1,13).reshape(3,4)
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])